app:
  name: "echto"
  env: "development"
  port: 8080
  host: "0.0.0.0"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  name: "echto"
  ssl_mode: "disable"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: "1h"

logging:
  level: "debug"
  format: "json"

jwt:
  secret: "your-secret-key"
  expire_hours: 24
